FROM python:3.9
COPY . /opt/siridb-enodo-hub
WORKDIR /opt/siridb-enodo-hub
RUN pip install -r requirements.txt

# Client (Socket) connections
EXPOSE 9103
# Web api and websockets
EXPOSE 80

# Volume mounts
VOLUME ["/data"]

# Overwrite default configuration parameters
ENV ENODO_HUB_BASE_PATH /data
ENV ENODO_HUB_INTERNAL_SOCKET_SERVER_PORT 9103
ENV ENODO_HUB_INTERNAL_SOCKET_SERVER_HOSTNAME 0.0.0.0
ENV ENODO_HUB_BASIC_AUTH_USERNAME enodo
ENV ENODO_HUB_BASIC_AUTH_PASSWORD enodo
ENV ENODO_HUB_CLIENT_MAX_TIMEOUT 35
ENV ENODO_HUB_SAVE_TO_DISK_INTERVAL 20
ENV ENODO_HUB_ENABLE_REST_API true
ENV ENODO_HUB_ENABLE_SOCKET_IO_API true
ENV ENODO_HUB_DISABLE_SAFE_MODE true
ENV ENODO_ANALYSER_WATCHER_INTERVAL 1
ENV ENODO_ANALYSER_SIRIDB_CONNECTION_CHECK_INTERVAL 30
ENV ENODO_ANALYSER_INTERVAL_SCHEDULES_SERIES 3600

CMD ["/opt/siridb-enodo-hub/main.py"]
ENTRYPOINT ["python"]
