DETECT_ANOMALIES_STATUS_REQUESTED = 1
DETECT_ANOMALIES_STATUS_PENDING = 2
DETECT_ANOMALIES_STATUS_DONE = 4
DETECT_ANOMALIES_STATUS_NONE = None
DETECT_ANOMALIES_STATUSES = [DETECT_ANOMALIES_STATUS_REQUESTED, DETECT_ANOMALIES_STATUS_PENDING,
                             DETECT_ANOMALIES_STATUS_DONE, DETECT_ANOMALIES_STATUS_NONE]

FORECAST_STATUS_NONE = 1
FORECAST_STATUS_PENDING = 2
FORECAST_STATUS_DONE = 3