JOB_TYPE_FORECAST_SERIE = 1
JOB_TYPE_DETECT_ANOMALIES_FOR_SERIE = 2
JOB_TYPE_BASE_SERIE_ANALYSES = 3

JOB_TYPES = [JOB_TYPE_BASE_SERIE_ANALYSES, JOB_TYPE_FORECAST_SERIE, JOB_TYPE_DETECT_ANOMALIES_FOR_SERIE]
